//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 02:55:44 PM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openclinica.org/ns/rules/v3.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openclinica.ns.rules.v31;
