//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 02:55:44 PM WIB 
//


package org.openclinica.ns.rules.v31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  The top level root element. Allows the definition of default values
 *                 for all nested bean definitions. 
 * 
 * <p>Java class for RuleImportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleImportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openclinica.org/ns/rules/v3.1}RuleAssignment" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.openclinica.org/ns/rules/v3.1}RuleDef" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleImportType", propOrder = {
    "ruleAssignment",
    "ruleDef"
})
public class RuleImportType {

    @XmlElement(name = "RuleAssignment", required = true)
    protected List<RuleAssignmentType> ruleAssignment;
    @XmlElement(name = "RuleDef")
    protected List<RuleDefType> ruleDef;

    /**
     * Gets the value of the ruleAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RuleAssignmentType }
     * 
     * 
     */
    public List<RuleAssignmentType> getRuleAssignment() {
        if (ruleAssignment == null) {
            ruleAssignment = new ArrayList<RuleAssignmentType>();
        }
        return this.ruleAssignment;
    }

    /**
     * Gets the value of the ruleDef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleDef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleDef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RuleDefType }
     * 
     * 
     */
    public List<RuleDefType> getRuleDef() {
        if (ruleDef == null) {
            ruleDef = new ArrayList<RuleDefType>();
        }
        return this.ruleDef;
    }

}
