//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 02:55:44 PM WIB 
//


package org.openclinica.ns.rules.v31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunOnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RunOnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="not_started" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="scheduled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="data_entry_started" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="complete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="skipped" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="stopped" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunOnType")
public class RunOnType {

    @XmlAttribute(name = "not_started", required = true)
    protected boolean notStarted;
    @XmlAttribute(name = "scheduled", required = true)
    protected boolean scheduled;
    @XmlAttribute(name = "data_entry_started", required = true)
    protected boolean dataEntryStarted;
    @XmlAttribute(name = "complete", required = true)
    protected boolean complete;
    @XmlAttribute(name = "skipped", required = true)
    protected boolean skipped;
    @XmlAttribute(name = "stopped", required = true)
    protected boolean stopped;

    /**
     * Gets the value of the notStarted property.
     * 
     */
    public boolean isNotStarted() {
        return notStarted;
    }

    /**
     * Sets the value of the notStarted property.
     * 
     */
    public void setNotStarted(boolean value) {
        this.notStarted = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     */
    public boolean isScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     */
    public void setScheduled(boolean value) {
        this.scheduled = value;
    }

    /**
     * Gets the value of the dataEntryStarted property.
     * 
     */
    public boolean isDataEntryStarted() {
        return dataEntryStarted;
    }

    /**
     * Sets the value of the dataEntryStarted property.
     * 
     */
    public void setDataEntryStarted(boolean value) {
        this.dataEntryStarted = value;
    }

    /**
     * Gets the value of the complete property.
     * 
     */
    public boolean isComplete() {
        return complete;
    }

    /**
     * Sets the value of the complete property.
     * 
     */
    public void setComplete(boolean value) {
        this.complete = value;
    }

    /**
     * Gets the value of the skipped property.
     * 
     */
    public boolean isSkipped() {
        return skipped;
    }

    /**
     * Sets the value of the skipped property.
     * 
     */
    public void setSkipped(boolean value) {
        this.skipped = value;
    }

    /**
     * Gets the value of the stopped property.
     * 
     */
    public boolean isStopped() {
        return stopped;
    }

    /**
     * Sets the value of the stopped property.
     * 
     */
    public void setStopped(boolean value) {
        this.stopped = value;
    }

}
