//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.30 at 09:52:30 PM WIB 
//


package org.openclinica.ns.rules.v31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunOnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RunOnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="not_scheduled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="scheduled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="data_entry_started" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="completed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="skipped" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="stopped" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="signed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunOnType")
public class RunOnType {

    @XmlAttribute(name = "not_scheduled", required = true)
    protected boolean notScheduled;
    @XmlAttribute(name = "scheduled", required = true)
    protected boolean scheduled;
    @XmlAttribute(name = "data_entry_started", required = true)
    protected boolean dataEntryStarted;
    @XmlAttribute(name = "completed", required = true)
    protected boolean completed;
    @XmlAttribute(name = "skipped", required = true)
    protected boolean skipped;
    @XmlAttribute(name = "stopped", required = true)
    protected boolean stopped;
    @XmlAttribute(name = "signed")
    protected Boolean signed;
    @XmlAttribute(name = "locked")
    protected Boolean locked;

    /**
     * Gets the value of the notScheduled property.
     * 
     */
    public boolean isNotScheduled() {
        return notScheduled;
    }

    /**
     * Sets the value of the notScheduled property.
     * 
     */
    public void setNotScheduled(boolean value) {
        this.notScheduled = value;
    }

    /**
     * Gets the value of the scheduled property.
     * 
     */
    public boolean isScheduled() {
        return scheduled;
    }

    /**
     * Sets the value of the scheduled property.
     * 
     */
    public void setScheduled(boolean value) {
        this.scheduled = value;
    }

    /**
     * Gets the value of the dataEntryStarted property.
     * 
     */
    public boolean isDataEntryStarted() {
        return dataEntryStarted;
    }

    /**
     * Sets the value of the dataEntryStarted property.
     * 
     */
    public void setDataEntryStarted(boolean value) {
        this.dataEntryStarted = value;
    }

    /**
     * Gets the value of the completed property.
     * 
     */
    public boolean isCompleted() {
        return completed;
    }

    /**
     * Sets the value of the completed property.
     * 
     */
    public void setCompleted(boolean value) {
        this.completed = value;
    }

    /**
     * Gets the value of the skipped property.
     * 
     */
    public boolean isSkipped() {
        return skipped;
    }

    /**
     * Sets the value of the skipped property.
     * 
     */
    public void setSkipped(boolean value) {
        this.skipped = value;
    }

    /**
     * Gets the value of the stopped property.
     * 
     */
    public boolean isStopped() {
        return stopped;
    }

    /**
     * Sets the value of the stopped property.
     * 
     */
    public void setStopped(boolean value) {
        this.stopped = value;
    }

    /**
     * Gets the value of the signed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSigned() {
        return signed;
    }

    /**
     * Sets the value of the signed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSigned(Boolean value) {
        this.signed = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocked(Boolean value) {
        this.locked = value;
    }

}
